### ISSUE TITLE
New organization for the website

### ISSUE THREAD

**Issue by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [maximousblk/piracy#2]
The idea would be to have bigger parent categories with their respective children, so you would click on Software and it would show you another web page than if you click on Providers, separating information and making it easier to read. I've added some notes and removed other stuff and give reasons for it, I think we can talk this through about how to continue with the organization. 

----

SOFTWARE
----

1. P2P Networks
 - Bittorrent Clients
   . Common clients
   . Terminal handled clients
   . Web clients
   . Tribler and I2P?
   . Client plugins
 - Other P2P Networks
2. Browser
 - Extensions
 - Userscripts
3. Antivirus (Not sure about this one, they are all sketchy and/or closed source.)
4. Decentralized Networks
5. Usenet
 - Usenet Indexing Software
 - Usenet Clients
6. Direct Downloads
 - Download Managers
 - DDL Tools
 - Custom Google Search Engines (I think this should not be added because of privacy issues, but it can be discussed.)
 - FTP Indexers
 - DDL Search Engines and Crawlers
 - DDL Link Sites
 - Premium Link Generators    These     }
 - Premium Link Hosts         should be }
 - Open Directories           researched}
7. Media Centre Applications
8. Automation Tools
 - TV Automation
 - Movie Automation
 - Music Automation
 - Subtitles Automation
9. Ripping, Transcoding, Converting, Encoding (We should find a better title, and maybe this should me merged with "File Renaming and Tagging"?)
10. Cloud Storage
11. File Sharing Tools
12. Stream Synchronisation
  
PROVIDERS
----

1. VPNs
 - Paid VPNs
 - Self-hosted VPNs
2. Seedboxes
 - Web-based Cloud Seedboxes
 - Seedbox Hosting Providers
3. Domain Names
4. Torrent Trackers (How should be deal with them not needing to be known for them to not be shuted down?)
 - Public
 - Semi Private
 - Private
 - Tracker Aggregators
 - Tracker Proxies
 - Tracker Frameworks
5. Usenet
 - Usenet Providers
 - Usenet Indexers
  . Paid Indexers
  . Free Indexers
6. Streaming Sites
 - HD Streaming
 - Big Media Libraries
 - TV
 - Anime
 - Cartoons
 - Sports Streaming
 - Specialty Sites
7. Third Party Hosts
8. Piracy Blogs, News and Fora
9. Content Discovery
10. Proxy Sites
 
 ----
 
Resources?
----

1. Tracker Invites
2. Seedbox Setup Tools and Guides
 
----
 
Removed:
[Password managers] Reason: Not related to piracy, but rather privacy, already covered by PT.
[Privacy category in general] Reason: Not related to piracy, but rather privacy, already covered by PT, we should link to PT somewhere.
[Operating Systems] Reason: Not related to piracy, but rather privacy, already covered by PT.
[Full Movies On] Reason: Most of the websites were subreddits which are probably all banned, and even though, this should be within the Streaming section.

----

Notes:
Should IRC category be listed?
Gaming, Music, EBooks and the rest of more specific categories should be disectioned and fitted under already existant, better ones.
Torrenting sections should be disectioned and separated in better categories.
Mobile Apps sections should be disectioned and separated in better categories.
Discord Servers should not be listed, or should be listed with a warning.
Telegram Piracy should not be listed, or should be listed with a warning.
Dashboards and Homepages should be investigated.
Miscellaneous should be investigated.
IPTV and DVR should be investigated.
DC++ should be investigated.

**Comment by maximousblk** [comment]
I'm currently merging [Igglybuff/awesome-piracy](https://github.com/Igglybuff/awesome-piracy) and [CHEF-KOCH/Warez](https://github.com/CHEF-KOCH/Warez) to create a bigger list.

Also the search only works with H2 and H3 tags and is not a full-text search (this is a problem with vuepress itself and maybe fixed in an update). that means it needs to have more general categories and lesser subcategories.

I'm going for something similar to:
- Privacy ( Make sure you don,t get caught )
- Movies
- TV
- Cartoon / Anime ( both together because many sources keep both )
- Comic / Manga ( both together because many sources keep both )
- Music
- Books
- Audiobooks
- Software
- Games

But I'm currently focusing on merging the two lists

**Comment by maximousblk** [comment]
@5a384507-18ce-417c-bb55-d4dfcc8883fe Is the current situation OK, or do you have any better suggestions?

**Comment by maximousblk** [comment]
Closing this because of in activity. This issue may be opened if any new suggestions come in.
