### ISSUE TITLE
Add plausible analytics

### ISSUE THREAD

**Issue by kylejwatson** [maximousblk/piracy#8]
Link: https://plausible.io/
Github: https://github.com/plausible/analytics
Description:
Plausible is a lightweight and open-source website analytics tool. It doesn’t use cookies and is fully compliant with GDPR, CCPA and PECR.

**Comment by maximousblk** [comment]
@kylejwatson Thank you.

I'm currently moving this website from vuepress to docusaurus v2. until then all the changes to the list will be held back.

you can check out the preview at https://warez.now.sh
